### ISSUE TITLE
-dr switch results in error

### ISSUE THREAD

**Issue by microcreators** [cr0hn/festin#1]
checking festin with this pattern
`festin -T 20 -dr *keyword* keyword.com` always results in:
```
Traceback (most recent call last):
  File "/usr/local/bin/festin", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/dist-packages/festin/__main__.py", line 446, in main
    parsed.domain_regex = re.compile(parsed.domain_regex)
  File "/usr/lib/python3.8/re.py", line 252, in compile
    return _compile(pattern, flags)
  File "/usr/lib/python3.8/re.py", line 304, in _compile
    p = sre_compile.compile(pattern, flags)
  File "/usr/lib/python3.8/sre_compile.py", line 764, in compile
    p = sre_parse.parse(p, flags)
  File "/usr/lib/python3.8/sre_parse.py", line 948, in parse
    p = _parse_sub(source, state, flags & SRE_FLAG_VERBOSE, 0)
  File "/usr/lib/python3.8/sre_parse.py", line 443, in _parse_sub
    itemsappend(_parse(source, state, verbose, nested + 1,
  File "/usr/lib/python3.8/sre_parse.py", line 668, in _parse
    raise source.error("nothing to repeat",
re.error: nothing to repeat at position 0
```
any idea what could help?

**Comment by cr0hn** [comment]
`*keyword*`  -> is not valid POSIX regex. Replace it with: `.keyword.`

I updated README to fix the example. Thx
