### ISSUE TITLE
Syntax Error

### ISSUE THREAD

**Issue by joeldeleep** [cr0hn/festin#3]
I installed the festin package using ```pip install festin```
While doing an enumeration I am getting the following error , the same is triggered for help section also 
```bash
$festin -h
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/bin/festin", line 5, in <module>
    from festin.__main__ import main
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/festin/__init__.py", line 4, in <module>
    from .analysis import *
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/festin/analysis.py", line 58
    if loc := urlparse(res).netloc:
            ^
SyntaxError: invalid syntax
```
I am running OSx and installed using python3

**Comment by cr0hn** [comment]
Festin requires Python 3.8 or higher. You also can use the Docker version
